version: "3.9"
services:
  client:
    build: "./services/client"
    restart: always
    environment:
      # keep in sync with Dockerfile
      EXPRESS_BASE_URL: $EXPRESS_BASE_URL
      NODE_ENV: $NODE_ENV
    ports:
      - "8000:80"
  server:
    build: "./services/server"
    restart: always
    environment:
      APP_BASE_URL: $APP_BASE_URL
      EXPRESS_SESSION_SECRET: $EXPRESS_SESSION_SECRET
      GITHUB_CALLBACK_PATH: $GITHUB_CALLBACK_PATH
      GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOSTNAME: $MySQL_HOSTNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USERNAME: $MYSQL_USERNAME
      NODE_ENV: $NODE_ENV
    ports:
      - "3000:3000"
  db:
    image: "mariadb:10.5"
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
  adminer:
    image: "adminer:4"
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
